<?php

/**
 * BasephPhoto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $filename
 * @property string $content_type
 * @property Doctrine_Collection $spSports
 * @property Doctrine_Collection $spPhoto
 * @property Doctrine_Collection $gaActivites
 * @property Doctrine_Collection $gaPhoto
 * @property coCotisant $coCotisant
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method string              getFilename()     Returns the current record's "filename" value
 * @method string              getContentType()  Returns the current record's "content_type" value
 * @method Doctrine_Collection getSpSports()     Returns the current record's "spSports" collection
 * @method Doctrine_Collection getSpPhoto()      Returns the current record's "spPhoto" collection
 * @method Doctrine_Collection getGaActivites()  Returns the current record's "gaActivites" collection
 * @method Doctrine_Collection getGaPhoto()      Returns the current record's "gaPhoto" collection
 * @method coCotisant          getCoCotisant()   Returns the current record's "coCotisant" value
 * @method phPhoto             setId()           Sets the current record's "id" value
 * @method phPhoto             setFilename()     Sets the current record's "filename" value
 * @method phPhoto             setContentType()  Sets the current record's "content_type" value
 * @method phPhoto             setSpSports()     Sets the current record's "spSports" collection
 * @method phPhoto             setSpPhoto()      Sets the current record's "spPhoto" collection
 * @method phPhoto             setGaActivites()  Sets the current record's "gaActivites" collection
 * @method phPhoto             setGaPhoto()      Sets the current record's "gaPhoto" collection
 * @method phPhoto             setCoCotisant()   Sets the current record's "coCotisant" value
 * 
 * @package    BDS
 * @subpackage model
 * @author     Ludovic Henry
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasephPhoto extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ph_photos');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('filename', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('content_type', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('spSport as spSports', array(
             'refClass' => 'spPhoto',
             'local' => 'photo_id',
             'foreign' => 'sport_id'));

        $this->hasMany('spPhoto', array(
             'local' => 'id',
             'foreign' => 'photo_id'));

        $this->hasMany('gaActivite as gaActivites', array(
             'refClass' => 'gaPhoto',
             'local' => 'photo_id',
             'foreign' => 'activite_id'));

        $this->hasMany('gaPhoto', array(
             'local' => 'id',
             'foreign' => 'photo_id'));

        $this->hasOne('coCotisant', array(
             'local' => 'id',
             'foreign' => 'photo_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}