<?php

/**
 * BaseelListe
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $siege_id
 * @property string $description
 * @property elSiege $siege
 * @property Doctrine_Collection $coCotisants
 * @property Doctrine_Collection $elCandidat
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method integer             getSiegeId()     Returns the current record's "siege_id" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method elSiege             getSiege()       Returns the current record's "siege" value
 * @method Doctrine_Collection getCoCotisants() Returns the current record's "coCotisants" collection
 * @method Doctrine_Collection getElCandidat()  Returns the current record's "elCandidat" collection
 * @method elListe             setId()          Sets the current record's "id" value
 * @method elListe             setSiegeId()     Sets the current record's "siege_id" value
 * @method elListe             setDescription() Sets the current record's "description" value
 * @method elListe             setSiege()       Sets the current record's "siege" value
 * @method elListe             setCoCotisants() Sets the current record's "coCotisants" collection
 * @method elListe             setElCandidat()  Sets the current record's "elCandidat" collection
 * 
 * @package    BDS
 * @subpackage model
 * @author     Ludovic Henry
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseelListe extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('el_listes');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('siege_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('elSiege as siege', array(
             'local' => 'siege_id',
             'foreign' => 'id',
             'onDelete' => 'cascade',
             'onUpdate' => 'cascade'));

        $this->hasMany('coCotisant as coCotisants', array(
             'refClass' => 'elCandidat',
             'local' => 'liste_id',
             'foreign' => 'cotisant_id'));

        $this->hasMany('elCandidat', array(
             'local' => 'id',
             'foreign' => 'liste_id'));
    }
}