<?php

/**
 * BaseacCommentaire
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $actualite_id
 * @property integer $cotisant_id
 * @property string $contenu
 * @property acActualite $actualite
 * @property coCotisant $coCotisant
 * 
 * @method integer       getId()           Returns the current record's "id" value
 * @method integer       getActualiteId()  Returns the current record's "actualite_id" value
 * @method integer       getCotisantId()   Returns the current record's "cotisant_id" value
 * @method string        getContenu()      Returns the current record's "contenu" value
 * @method acActualite   getActualite()    Returns the current record's "actualite" value
 * @method coCotisant    getCoCotisant()   Returns the current record's "coCotisant" value
 * @method acCommentaire setId()           Sets the current record's "id" value
 * @method acCommentaire setActualiteId()  Sets the current record's "actualite_id" value
 * @method acCommentaire setCotisantId()   Sets the current record's "cotisant_id" value
 * @method acCommentaire setContenu()      Sets the current record's "contenu" value
 * @method acCommentaire setActualite()    Sets the current record's "actualite" value
 * @method acCommentaire setCoCotisant()   Sets the current record's "coCotisant" value
 * 
 * @package    BDS
 * @subpackage model
 * @author     Ludovic Henry
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseacCommentaire extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ac_commentaires');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('actualite_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('cotisant_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('contenu', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('acActualite as actualite', array(
             'local' => 'actualite_id',
             'foreign' => 'id',
             'onDelete' => 'cascade',
             'onUpdate' => 'cascade'));

        $this->hasOne('coCotisant', array(
             'local' => 'cotisant_id',
             'foreign' => 'id',
             'onDelete' => 'set null',
             'onUpdate' => 'cascade'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}