<?php

/**
 * BaseelSiege
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $poste_id
 * @property integer $election_id
 * @property elPoste $poste
 * @property elElection $election
 * @property Doctrine_Collection $listes
 * @property Doctrine_Collection $votes
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method integer             getPosteId()     Returns the current record's "poste_id" value
 * @method integer             getElectionId()  Returns the current record's "election_id" value
 * @method elPoste             getPoste()       Returns the current record's "poste" value
 * @method elElection          getElection()    Returns the current record's "election" value
 * @method Doctrine_Collection getListes()      Returns the current record's "listes" collection
 * @method Doctrine_Collection getVotes()       Returns the current record's "votes" collection
 * @method elSiege             setId()          Sets the current record's "id" value
 * @method elSiege             setPosteId()     Sets the current record's "poste_id" value
 * @method elSiege             setElectionId()  Sets the current record's "election_id" value
 * @method elSiege             setPoste()       Sets the current record's "poste" value
 * @method elSiege             setElection()    Sets the current record's "election" value
 * @method elSiege             setListes()      Sets the current record's "listes" collection
 * @method elSiege             setVotes()       Sets the current record's "votes" collection
 * 
 * @package    BDS
 * @subpackage model
 * @author     Ludovic Henry
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseelSiege extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('el_sieges');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('poste_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('election_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('elPoste as poste', array(
             'local' => 'poste_id',
             'foreign' => 'id',
             'onDelete' => 'cascade',
             'onUpdate' => 'cascade'));

        $this->hasOne('elElection as election', array(
             'local' => 'election_id',
             'foreign' => 'id',
             'onDelete' => 'cascade',
             'onUpdate' => 'cascade'));

        $this->hasMany('elListe as listes', array(
             'local' => 'id',
             'foreign' => 'siege_id'));

        $this->hasMany('elVote as votes', array(
             'local' => 'id',
             'foreign' => 'siege_id'));
    }
}