<?php

/**
 * BasesuBugTracker
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property date $deadline
 * @property string $statut
 * @property string $problem
 * 
 * @method integer      getId()       Returns the current record's "id" value
 * @method date         getDeadline() Returns the current record's "deadline" value
 * @method string       getStatut()   Returns the current record's "statut" value
 * @method string       getProblem()  Returns the current record's "problem" value
 * @method suBugTracker setId()       Sets the current record's "id" value
 * @method suBugTracker setDeadline() Sets the current record's "deadline" value
 * @method suBugTracker setStatut()   Sets the current record's "statut" value
 * @method suBugTracker setProblem()  Sets the current record's "problem" value
 * 
 * @package    BDS
 * @subpackage model
 * @author     Ludovic Henry
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesuBugTracker extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('su_bugs_tracker');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('deadline', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('statut', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('problem', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}