<?php

/**
 * BasewmWeekmail
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $objet
 * @property string $introduction
 * @property string $blague
 * @property string $conclusion
 * @property Doctrine_Collection $paragraphes
 * @property Doctrine_Collection $pieces_jointes
 * 
 * @method integer             getId()             Returns the current record's "id" value
 * @method string              getObjet()          Returns the current record's "objet" value
 * @method string              getIntroduction()   Returns the current record's "introduction" value
 * @method string              getBlague()         Returns the current record's "blague" value
 * @method string              getConclusion()     Returns the current record's "conclusion" value
 * @method Doctrine_Collection getParagraphes()    Returns the current record's "paragraphes" collection
 * @method Doctrine_Collection getPiecesJointes()  Returns the current record's "pieces_jointes" collection
 * @method wmWeekmail          setId()             Sets the current record's "id" value
 * @method wmWeekmail          setObjet()          Sets the current record's "objet" value
 * @method wmWeekmail          setIntroduction()   Sets the current record's "introduction" value
 * @method wmWeekmail          setBlague()         Sets the current record's "blague" value
 * @method wmWeekmail          setConclusion()     Sets the current record's "conclusion" value
 * @method wmWeekmail          setParagraphes()    Sets the current record's "paragraphes" collection
 * @method wmWeekmail          setPiecesJointes()  Sets the current record's "pieces_jointes" collection
 * 
 * @package    BDS
 * @subpackage model
 * @author     Ludovic Henry
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasewmWeekmail extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('wm_weekmails');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('objet', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('introduction', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('blague', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('conclusion', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('wmParagraphe as paragraphes', array(
             'local' => 'id',
             'foreign' => 'weekmail_id'));

        $this->hasMany('wmPieceJointe as pieces_jointes', array(
             'local' => 'id',
             'foreign' => 'weekmail_id'));
    }
}