<?php

/**
 * BasemlSport
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property spSport $spSport
 * 
 * @method spSport getSpSport() Returns the current record's "spSport" value
 * @method mlSport setSpSport() Sets the current record's "spSport" value
 * 
 * @package    BDS
 * @subpackage model
 * @author     Ludovic Henry
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasemlSport extends mlMail
{
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('spSport', array(
             'local' => 'sport_id',
             'foreign' => 'id',
             'onDelete' => 'set null',
             'onUpdate' => 'cascade'));
    }
}