<?php

/**
 * BaseelPoste
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nom
 * @property string $description
 * @property Doctrine_Collection $elections
 * @property Doctrine_Collection $sieges
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getNom()         Returns the current record's "nom" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method Doctrine_Collection getElections()   Returns the current record's "elections" collection
 * @method Doctrine_Collection getSieges()      Returns the current record's "sieges" collection
 * @method elPoste             setId()          Sets the current record's "id" value
 * @method elPoste             setNom()         Sets the current record's "nom" value
 * @method elPoste             setDescription() Sets the current record's "description" value
 * @method elPoste             setElections()   Sets the current record's "elections" collection
 * @method elPoste             setSieges()      Sets the current record's "sieges" collection
 * 
 * @package    BDS
 * @subpackage model
 * @author     Ludovic Henry
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseelPoste extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('el_postes');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('nom', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('elElection as elections', array(
             'refClass' => 'elSiege',
             'local' => 'poste_id',
             'foreign' => 'election_id'));

        $this->hasMany('elSiege as sieges', array(
             'local' => 'id',
             'foreign' => 'poste_id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'name' => 'slug',
             'fields' => 
             array(
              0 => 'nom',
             ),
             'unique' => true,
             'canUpdate' => true,
             ));
        $this->actAs($sluggable0);
    }
}