<?php

/**
 * BasemlMail
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $cotisant_id
 * @property string $objet
 * @property string $destinataires
 * @property string $contenu
 * @property timestamp $sent_at
 * @property string $type
 * @property integer $sport_id
 * @property integer $activite_id
 * @property coCotisant $coCotisant
 * 
 * @method integer    getId()            Returns the current record's "id" value
 * @method integer    getCotisantId()    Returns the current record's "cotisant_id" value
 * @method string     getObjet()         Returns the current record's "objet" value
 * @method string     getDestinataires() Returns the current record's "destinataires" value
 * @method string     getContenu()       Returns the current record's "contenu" value
 * @method timestamp  getSentAt()        Returns the current record's "sent_at" value
 * @method string     getType()          Returns the current record's "type" value
 * @method integer    getSportId()       Returns the current record's "sport_id" value
 * @method integer    getActiviteId()    Returns the current record's "activite_id" value
 * @method coCotisant getCoCotisant()    Returns the current record's "coCotisant" value
 * @method mlMail     setId()            Sets the current record's "id" value
 * @method mlMail     setCotisantId()    Sets the current record's "cotisant_id" value
 * @method mlMail     setObjet()         Sets the current record's "objet" value
 * @method mlMail     setDestinataires() Sets the current record's "destinataires" value
 * @method mlMail     setContenu()       Sets the current record's "contenu" value
 * @method mlMail     setSentAt()        Sets the current record's "sent_at" value
 * @method mlMail     setType()          Sets the current record's "type" value
 * @method mlMail     setSportId()       Sets the current record's "sport_id" value
 * @method mlMail     setActiviteId()    Sets the current record's "activite_id" value
 * @method mlMail     setCoCotisant()    Sets the current record's "coCotisant" value
 * 
 * @package    BDS
 * @subpackage model
 * @author     Ludovic Henry
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasemlMail extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ml_mails');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('cotisant_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('objet', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('destinataires', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'Aucun destinaraires',
             ));
        $this->hasColumn('contenu', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('sent_at', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('type', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('sport_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('activite_id', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->setSubClasses(array(
             'mlWeekmail' => 
             array(
              'type' => 'mlWeekmail',
             ),
             'mlSport' => 
             array(
              'type' => 'mlSport',
             ),
             'mlActivite' => 
             array(
              'type' => 'mlActivite',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('coCotisant', array(
             'local' => 'cotisant_id',
             'foreign' => 'id',
             'onDelete' => 'set null',
             'onUpdate' => 'cascade'));
    }
}