<?php

/**
 * BasegaPhoto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $activite_id
 * @property integer $photo_id
 * @property gaActivite $activite
 * @property phPhoto $phPhoto
 * 
 * @method integer    getActiviteId()  Returns the current record's "activite_id" value
 * @method integer    getPhotoId()     Returns the current record's "photo_id" value
 * @method gaActivite getActivite()    Returns the current record's "activite" value
 * @method phPhoto    getPhPhoto()     Returns the current record's "phPhoto" value
 * @method gaPhoto    setActiviteId()  Sets the current record's "activite_id" value
 * @method gaPhoto    setPhotoId()     Sets the current record's "photo_id" value
 * @method gaPhoto    setActivite()    Sets the current record's "activite" value
 * @method gaPhoto    setPhPhoto()     Sets the current record's "phPhoto" value
 * 
 * @package    BDS
 * @subpackage model
 * @author     Ludovic Henry
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasegaPhoto extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ga_photos');
        $this->hasColumn('activite_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('photo_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('gaActivite as activite', array(
             'local' => 'activite_id',
             'foreign' => 'id',
             'onDelete' => 'cascade',
             'onUpdate' => 'cascade'));

        $this->hasOne('phPhoto', array(
             'local' => 'photo_id',
             'foreign' => 'id',
             'onDelete' => 'cascade',
             'onUpdate' => 'cascade'));
    }
}