<?php

/**
 * BaseacActualiteTag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $actualite_id
 * @property integer $tag_id
 * @property acTag $tag
 * @property acActualite $actualite
 * 
 * @method integer        getActualiteId()  Returns the current record's "actualite_id" value
 * @method integer        getTagId()        Returns the current record's "tag_id" value
 * @method acTag          getTag()          Returns the current record's "tag" value
 * @method acActualite    getActualite()    Returns the current record's "actualite" value
 * @method acActualiteTag setActualiteId()  Sets the current record's "actualite_id" value
 * @method acActualiteTag setTagId()        Sets the current record's "tag_id" value
 * @method acActualiteTag setTag()          Sets the current record's "tag" value
 * @method acActualiteTag setActualite()    Sets the current record's "actualite" value
 * 
 * @package    BDS
 * @subpackage model
 * @author     Ludovic Henry
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseacActualiteTag extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ac_actualites_tags');
        $this->hasColumn('actualite_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('tag_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('acTag as tag', array(
             'local' => 'tag_id',
             'foreign' => 'id',
             'onDelete' => 'cascade',
             'onUpdate' => 'cascade'));

        $this->hasOne('acActualite as actualite', array(
             'local' => 'actualite_id',
             'foreign' => 'id',
             'onDelete' => 'cascade',
             'onUpdate' => 'cascade'));
    }
}