<?php

/**
 * BaseelCandidat
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $liste_id
 * @property integer $cotisant_id
 * @property coCotisant $coCotisant
 * @property elListe $liste
 * 
 * @method integer    getListeId()     Returns the current record's "liste_id" value
 * @method integer    getCotisantId()  Returns the current record's "cotisant_id" value
 * @method coCotisant getCoCotisant()  Returns the current record's "coCotisant" value
 * @method elListe    getListe()       Returns the current record's "liste" value
 * @method elCandidat setListeId()     Sets the current record's "liste_id" value
 * @method elCandidat setCotisantId()  Sets the current record's "cotisant_id" value
 * @method elCandidat setCoCotisant()  Sets the current record's "coCotisant" value
 * @method elCandidat setListe()       Sets the current record's "liste" value
 * 
 * @package    BDS
 * @subpackage model
 * @author     Ludovic Henry
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseelCandidat extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('el_listes_cotisants');
        $this->hasColumn('liste_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('cotisant_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('coCotisant', array(
             'local' => 'cotisant_id',
             'foreign' => 'id',
             'onDelete' => 'cascade',
             'onUpdate' => 'cascade'));

        $this->hasOne('elListe as liste', array(
             'local' => 'liste_id',
             'foreign' => 'id',
             'onDelete' => 'cascade',
             'onUpdate' => 'cascade'));
    }
}