<?php

/**
 * BasemlMailingListDestinataire
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $list_id
 * @property integer $cotisant_id
 * @property coCotisant $coCotisant
 * @property mlMailingList $list
 * 
 * @method integer                   getListId()      Returns the current record's "list_id" value
 * @method integer                   getCotisantId()  Returns the current record's "cotisant_id" value
 * @method coCotisant                getCoCotisant()  Returns the current record's "coCotisant" value
 * @method mlMailingList             getList()        Returns the current record's "list" value
 * @method mlMailingListDestinataire setListId()      Sets the current record's "list_id" value
 * @method mlMailingListDestinataire setCotisantId()  Sets the current record's "cotisant_id" value
 * @method mlMailingListDestinataire setCoCotisant()  Sets the current record's "coCotisant" value
 * @method mlMailingListDestinataire setList()        Sets the current record's "list" value
 * 
 * @package    BDS
 * @subpackage model
 * @author     Ludovic Henry
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasemlMailingListDestinataire extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ml_mailing_lists_destinataires');
        $this->hasColumn('list_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('cotisant_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('coCotisant', array(
             'local' => 'cotisant_id',
             'foreign' => 'id',
             'onDelete' => 'cascade',
             'onUpdate' => 'cascade'));

        $this->hasOne('mlMailingList as list', array(
             'local' => 'list_id',
             'foreign' => 'id',
             'onDelete' => 'cascade',
             'onUpdate' => 'cascade'));
    }
}