<?php

/**
 * BasemlActivite
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property gaActivite $gaActivite
 * 
 * @method gaActivite getGaActivite() Returns the current record's "gaActivite" value
 * @method mlActivite setGaActivite() Sets the current record's "gaActivite" value
 * 
 * @package    BDS
 * @subpackage model
 * @author     Ludovic Henry
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasemlActivite extends mlMail
{
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('gaActivite', array(
             'local' => 'activite_id',
             'foreign' => 'id',
             'onDelete' => 'set null',
             'onUpdate' => 'cascade'));
    }
}