<?php

/**
 * BasespHoraire
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $sport_id
 * @property integer $salle_id
 * @property integer $statut_id
 * @property integer $jour
 * @property time $heure_debut
 * @property time $heure_fin
 * @property spSport $sport
 * @property spSalle $salle
 * @property spHoraireStatut $statut
 * 
 * @method integer         getId()          Returns the current record's "id" value
 * @method integer         getSportId()     Returns the current record's "sport_id" value
 * @method integer         getSalleId()     Returns the current record's "salle_id" value
 * @method integer         getStatutId()    Returns the current record's "statut_id" value
 * @method integer         getJour()        Returns the current record's "jour" value
 * @method time            getHeureDebut()  Returns the current record's "heure_debut" value
 * @method time            getHeureFin()    Returns the current record's "heure_fin" value
 * @method spSport         getSport()       Returns the current record's "sport" value
 * @method spSalle         getSalle()       Returns the current record's "salle" value
 * @method spHoraireStatut getStatut()      Returns the current record's "statut" value
 * @method spHoraire       setId()          Sets the current record's "id" value
 * @method spHoraire       setSportId()     Sets the current record's "sport_id" value
 * @method spHoraire       setSalleId()     Sets the current record's "salle_id" value
 * @method spHoraire       setStatutId()    Sets the current record's "statut_id" value
 * @method spHoraire       setJour()        Sets the current record's "jour" value
 * @method spHoraire       setHeureDebut()  Sets the current record's "heure_debut" value
 * @method spHoraire       setHeureFin()    Sets the current record's "heure_fin" value
 * @method spHoraire       setSport()       Sets the current record's "sport" value
 * @method spHoraire       setSalle()       Sets the current record's "salle" value
 * @method spHoraire       setStatut()      Sets the current record's "statut" value
 * 
 * @package    BDS
 * @subpackage model
 * @author     Ludovic Henry
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasespHoraire extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sp_horaires');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('sport_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('salle_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('statut_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 1,
             ));
        $this->hasColumn('jour', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('heure_debut', 'time', null, array(
             'type' => 'time',
             'notnull' => true,
             ));
        $this->hasColumn('heure_fin', 'time', null, array(
             'type' => 'time',
             'notnull' => true,
             ));

        $this->check('heure_fin > heure_debut');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('spSport as sport', array(
             'local' => 'sport_id',
             'foreign' => 'id',
             'onDelete' => 'cascade',
             'onUpdate' => 'cascade'));

        $this->hasOne('spSalle as salle', array(
             'local' => 'salle_id',
             'foreign' => 'id',
             'onDelete' => 'cascade',
             'onUpdate' => 'cascade'));

        $this->hasOne('spHoraireStatut as statut', array(
             'local' => 'statut_id',
             'foreign' => 'id',
             'onDelete' => 'set default',
             'onUpdate' => 'cascade'));
    }
}