<?php

/**
 * BasemlAttachment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $mail_id
 * @property string $filename
 * @property string $nom
 * @property mlWeekmail $weekmail
 * 
 * @method integer      getId()       Returns the current record's "id" value
 * @method integer      getMailId()   Returns the current record's "mail_id" value
 * @method string       getFilename() Returns the current record's "filename" value
 * @method string       getNom()      Returns the current record's "nom" value
 * @method mlWeekmail   getWeekmail() Returns the current record's "weekmail" value
 * @method mlAttachment setId()       Sets the current record's "id" value
 * @method mlAttachment setMailId()   Sets the current record's "mail_id" value
 * @method mlAttachment setFilename() Sets the current record's "filename" value
 * @method mlAttachment setNom()      Sets the current record's "nom" value
 * @method mlAttachment setWeekmail() Sets the current record's "weekmail" value
 * 
 * @package    BDS
 * @subpackage model
 * @author     Ludovic Henry
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasemlAttachment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ml_attachments');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('mail_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('filename', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('nom', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('mlWeekmail as weekmail', array(
             'local' => 'mail_id',
             'foreign' => 'id',
             'onDelete' => 'cascade',
             'onUpdate' => 'cascade'));
    }
}