<?php

/**
 * BasewmPieceJointe
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $weekmail_id
 * @property string $nom
 * @property string $filename
 * @property wmWeekmail $weekmail
 * 
 * @method integer       getId()          Returns the current record's "id" value
 * @method integer       getWeekmailId()  Returns the current record's "weekmail_id" value
 * @method string        getNom()         Returns the current record's "nom" value
 * @method string        getFilename()    Returns the current record's "filename" value
 * @method wmWeekmail    getWeekmail()    Returns the current record's "weekmail" value
 * @method wmPieceJointe setId()          Sets the current record's "id" value
 * @method wmPieceJointe setWeekmailId()  Sets the current record's "weekmail_id" value
 * @method wmPieceJointe setNom()         Sets the current record's "nom" value
 * @method wmPieceJointe setFilename()    Sets the current record's "filename" value
 * @method wmPieceJointe setWeekmail()    Sets the current record's "weekmail" value
 * 
 * @package    BDS
 * @subpackage model
 * @author     Ludovic Henry
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasewmPieceJointe extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('wm_pieces_jointes');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('weekmail_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('nom', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('filename', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('wmWeekmail as weekmail', array(
             'local' => 'weekmail_id',
             'foreign' => 'id',
             'onDelete' => 'cascade',
             'onUpdate' => 'cascade'));
    }
}