<?php

/**
 * BasespHoraireStatut
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nom
 * @property string $couleur
 * @property boolean $is_ouvert
 * @property Doctrine_Collection $horaires
 * 
 * @method integer             getId()        Returns the current record's "id" value
 * @method string              getNom()       Returns the current record's "nom" value
 * @method string              getCouleur()   Returns the current record's "couleur" value
 * @method boolean             getIsOuvert()  Returns the current record's "is_ouvert" value
 * @method Doctrine_Collection getHoraires()  Returns the current record's "horaires" collection
 * @method spHoraireStatut     setId()        Sets the current record's "id" value
 * @method spHoraireStatut     setNom()       Sets the current record's "nom" value
 * @method spHoraireStatut     setCouleur()   Sets the current record's "couleur" value
 * @method spHoraireStatut     setIsOuvert()  Sets the current record's "is_ouvert" value
 * @method spHoraireStatut     setHoraires()  Sets the current record's "horaires" collection
 * 
 * @package    BDS
 * @subpackage model
 * @author     Ludovic Henry
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasespHoraireStatut extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sp_horaires_statuts');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('nom', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('couleur', 'string', 6, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '00FF00',
             'length' => 6,
             ));
        $this->hasColumn('is_ouvert', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('spHoraire as horaires', array(
             'local' => 'id',
             'foreign' => 'statut_id'));
    }
}