<?php

/**
 * BasemlWeekmail
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Doctrine_Collection $attachments
 * 
 * @method Doctrine_Collection getAttachments() Returns the current record's "attachments" collection
 * @method mlWeekmail          setAttachments() Sets the current record's "attachments" collection
 * 
 * @package    BDS
 * @subpackage model
 * @author     Ludovic Henry
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasemlWeekmail extends mlMail
{
    public function setUp()
    {
        parent::setUp();
        $this->hasMany('mlAttachment as attachments', array(
             'local' => 'id',
             'foreign' => 'mail_id'));
    }
}