<?php

/**
 * BaseacTag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nom
 * @property Doctrine_Collection $actualites
 * @property Doctrine_Collection $actualiteTags
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method string              getNom()           Returns the current record's "nom" value
 * @method Doctrine_Collection getActualites()    Returns the current record's "actualites" collection
 * @method Doctrine_Collection getActualiteTags() Returns the current record's "actualiteTags" collection
 * @method acTag               setId()            Sets the current record's "id" value
 * @method acTag               setNom()           Sets the current record's "nom" value
 * @method acTag               setActualites()    Sets the current record's "actualites" collection
 * @method acTag               setActualiteTags() Sets the current record's "actualiteTags" collection
 * 
 * @package    BDS
 * @subpackage model
 * @author     Ludovic Henry
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseacTag extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ac_tags');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('nom', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('acActualite as actualites', array(
             'refClass' => 'acActualiteTag',
             'local' => 'tag_id',
             'foreign' => 'actualite_id'));

        $this->hasMany('acActualiteTag as actualiteTags', array(
             'local' => 'id',
             'foreign' => 'tag_id'));
    }
}