<?php

/**
 * BasewmParagraphe
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $weekmail_id
 * @property string $titre
 * @property string $contenu
 * @property boolean $is_valide
 * @property wmWeekmail $weekmail
 * 
 * @method integer      getId()          Returns the current record's "id" value
 * @method integer      getWeekmailId()  Returns the current record's "weekmail_id" value
 * @method string       getTitre()       Returns the current record's "titre" value
 * @method string       getContenu()     Returns the current record's "contenu" value
 * @method boolean      getIsValide()    Returns the current record's "is_valide" value
 * @method wmWeekmail   getWeekmail()    Returns the current record's "weekmail" value
 * @method wmParagraphe setId()          Sets the current record's "id" value
 * @method wmParagraphe setWeekmailId()  Sets the current record's "weekmail_id" value
 * @method wmParagraphe setTitre()       Sets the current record's "titre" value
 * @method wmParagraphe setContenu()     Sets the current record's "contenu" value
 * @method wmParagraphe setIsValide()    Sets the current record's "is_valide" value
 * @method wmParagraphe setWeekmail()    Sets the current record's "weekmail" value
 * 
 * @package    BDS
 * @subpackage model
 * @author     Ludovic Henry
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasewmParagraphe extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('wm_paragraphes');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('weekmail_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('titre', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('contenu', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('is_valide', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('wmWeekmail as weekmail', array(
             'local' => 'weekmail_id',
             'foreign' => 'id',
             'onDelete' => 'cascade',
             'onUpdate' => 'cascade'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}