<?php

/**
 * BasefiDossier
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nom
 * @property Doctrine_Collection $fichiers
 * 
 * @method integer             getId()       Returns the current record's "id" value
 * @method string              getNom()      Returns the current record's "nom" value
 * @method Doctrine_Collection getFichiers() Returns the current record's "fichiers" collection
 * @method fiDossier           setId()       Sets the current record's "id" value
 * @method fiDossier           setNom()      Sets the current record's "nom" value
 * @method fiDossier           setFichiers() Sets the current record's "fichiers" collection
 * 
 * @package    BDS
 * @subpackage model
 * @author     Ludovic Henry
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasefiDossier extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('fi_dossiers');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('nom', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('fiFifichier as fichiers', array(
             'local' => 'id',
             'foreign' => 'dossier_id'));

        $nestedset0 = new Doctrine_Template_NestedSet(array(
             ));
        $this->actAs($nestedset0);
    }
}