<?php

/**
 * BaseelListe
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $poste_id
 * @property integer $election_id
 * @property string $description
 * @property elPoste $poste
 * @property elElection $election
 * @property Doctrine_Collection $coCotisants
 * @property Doctrine_Collection $elCandidat
 * @property Doctrine_Collection $elVote
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method integer             getPosteId()     Returns the current record's "poste_id" value
 * @method integer             getElectionId()  Returns the current record's "election_id" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method elPoste             getPoste()       Returns the current record's "poste" value
 * @method elElection          getElection()    Returns the current record's "election" value
 * @method Doctrine_Collection getCoCotisants() Returns the current record's "coCotisants" collection
 * @method Doctrine_Collection getElCandidat()  Returns the current record's "elCandidat" collection
 * @method Doctrine_Collection getElVote()      Returns the current record's "elVote" collection
 * @method elListe             setId()          Sets the current record's "id" value
 * @method elListe             setPosteId()     Sets the current record's "poste_id" value
 * @method elListe             setElectionId()  Sets the current record's "election_id" value
 * @method elListe             setDescription() Sets the current record's "description" value
 * @method elListe             setPoste()       Sets the current record's "poste" value
 * @method elListe             setElection()    Sets the current record's "election" value
 * @method elListe             setCoCotisants() Sets the current record's "coCotisants" collection
 * @method elListe             setElCandidat()  Sets the current record's "elCandidat" collection
 * @method elListe             setElVote()      Sets the current record's "elVote" collection
 * 
 * @package    BDS
 * @subpackage model
 * @author     Ludovic Henry
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseelListe extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('el_listes');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('poste_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('election_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('elPoste as poste', array(
             'local' => 'poste_id',
             'foreign' => 'id',
             'onDelete' => 'cascade',
             'onUpdate' => 'cascade'));

        $this->hasOne('elElection as election', array(
             'local' => 'election_id',
             'foreign' => 'id',
             'onDelete' => 'cascade',
             'onUpdate' => 'cascade'));

        $this->hasMany('coCotisant as coCotisants', array(
             'refClass' => 'elCandidat',
             'local' => 'liste_id',
             'foreign' => 'cotisant_id'));

        $this->hasMany('elCandidat', array(
             'local' => 'id',
             'foreign' => 'liste_id'));

        $this->hasMany('elVote', array(
             'local' => 'id',
             'foreign' => 'liste_id'));
    }
}