<?php

/**
 * acActualiteTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    BDS
 * @subpackage table
 * @author     Ludovic Henry
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class acActualiteTable extends Doctrine_Table {

    /**
     *
     * @return acActualiteTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('acActualite');
    }

    /**
     * Retrieve a acActualite object
     * This is the function called by sfDoctrineRoute->getObject()
     *
     * @param Doctrine_Query $q
     * @return acActualite
     */
    public function retrieveRouteObject(Doctrine_Query $q) {
        $a = $q->getRootAlias();

        return $q->leftJoin($a . '.tags')
                ->leftJoin($a . '.coCotisant')
                ->fetchOne();
    }

    /**
     * Retrieve a collection of acActualite
     * This function is called in the backend
     *
     * @param Doctrine_Query $q
     * @return Doctrine_Query
     */
    public function retrieveBackendList(Doctrine_Query $q) {
        return $q->leftJoin($q->getRootAlias() . '.coCotisant');
    }

}