<?php

/**
 * acActualiteTagTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    BDS
 * @subpackage table
 * @author     Ludovic Henry
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class acActualiteTagTable extends Doctrine_Table {

    /**
     * @return acActualiteTagTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('acActualiteTag');
    }

}