<?php

/**
 * acCommentaire
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    BDS
 * @subpackage model
 * @author     Ludovic Henry
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class acCommentaire extends BaseacCommentaire {

    /**
     * @return timestamp
     */
    public function getUpdatedAt() {
        return is_null($this->_get('updated_at')) ? $this->getCreatedAt() : $this->_get('updated_at');
    }

    /**
     * Get the titre_slug of the corresponding acActualite
     *
     * @return string
     */
    public function getActualiteTitreSlug() {
        return $this->getActualite()->getTitreSlug();
    }

    /**
     * @return string
     */
    public function getFormatedDate() {
        return format_date($this->getUpdatedAt(), 'g');
    }

    /**
     * @return string The 'contenu' of this commentaire without any tags
     */
    public function getStripContenu() {
        return preg_replace('|[[\/\!]*?[^\[\]]*?]|si', '', $this->getContenu());
    }

}