<?php

/**
 * acCommentaireTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    BDS
 * @subpackage table
 * @author     Ludovic Henry
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class acCommentaireTable extends Doctrine_Table {

    /**
     * @return acCommentaireTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('acCommentaire');
    }

    /**
     * Retrieve a collection of acCommentaire
     *
     * @param array $filters
     * @return Doctrine_Collection
     */
    public function retrieveListQuery(array $filters = array()) {
        $q = Doctrine_Query::create()
                        ->from('acCommentaire c')
                        ->leftJoin('c.coCotisant')
                        ->innerJoin('c.actualite')
                        ->orderBy('c.created_at ASC');

        foreach ( $filters as $key => $value )
            $q->andWhere("c.$key = ?", $value);

        return $q;
    }

    /**
     * Retrieve a collection of coCommentaire
     * This function is called in the backend
     *
     * @param Doctrine_Query $q
     * @return Doctrine_Query
     */
    public function retrieveBackendList(Doctrine_Query $q) {
        $a = $q->getRootAlias();

        return $q->leftJoin($a . '.coCotisant')
                ->leftJoin($a . '.actualite');
    }

}