<?php

/**
 * coCotisant
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    BDS
 * @subpackage model
 * @author     Ludovic Henry
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class coCotisant extends BasecoCotisant {

    public function getDateFinCotisation() {
        $semestre_fin_cotisation = $this->getSemestreFinCotisation();

        if (substr($semestre_fin_cotisation, 0, 1) === 'A')
            return '15-02-20' . (substr($semestre_fin_cotisation, 1, 2) + 1);
        else
            return '15-07-20' . substr($semestre_fin_cotisation, 1, 2);
    }

    /**
     * Retrieve if the 'coCotisant' has a certificat or not. This method is used in the backend
     *
     * @return string
     */
    public function hasCertificat() {
        return $this->_get('certificat') !== null;
    }

    /**
     * Retrieve if the 'coCotisant' has a photo or not
     * 
     * @return boolean
     */
    public function hasPhoto() {
        return $this->_get('photo') !== null;
    }

    public function isActif() {
        return $this->getIsActif();
    }

    /**
     * The string representation of this object
     *
     * @return  string
     */
    public function __toString() {
        return trim($this->_get('prenom') . ' ' . $this->_get('nom'));
    }

}
