<?php

/**
 * elElectionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class elElectionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object elElectionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('elElection');
    }
}