<?php

/**
 * elListeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class elListeTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object elListeTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('elListe');
    }

    public function retrieveListBackend(Doctrine_Query $q) {
        return $q;
    }

}