<?php

/**
 * elPosteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class elPosteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object elPosteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('elPoste');
    }
}