<?php

/**
 * elSiegeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class elSiegeTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object elSiegeTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('elSiege');
    }

}