<?php

/**
 * elVoteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class elVoteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object elVoteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('elVote');
    }
}