<?php

/**
 * fiDossierTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class fiDossierTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object fiDossierTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('fiDossier');
    }
}