<?php

/**
 * fiFifichierTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class fiFifichierTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object fiFifichierTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('fiFifichier');
    }
}