<?php

/**
 * gaActivite
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    BDS
 * @subpackage model
 * @author     Ludovic Henry
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class gaActivite extends BasegaActivite {

    /**
     * The string representation of this object
     *
     * @return  string
     */
    public function __toString() {
        return $this->getNom();
    }

    /**
     * Check if a coCotisant is participating to a gaActivite
     *
     * @param integer $user_id
     * @return bool
     */
    public function isAdmin(coCotisant $user) {
        return Doctrine_Query::create()
                ->from('gaParticipant p')
                ->where('p.cotisant_id = ?', $user->getId())
                ->andWhere('p.activite_id = ?', $this->getId())
                ->andWhere('p.is_admin = true')
                ->count() === 1;
    }

}
