<?php

/**
 * gaActiviteTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    BDS
 * @subpackage table
 * @author     Ludovic Henry
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class gaActiviteTable extends Doctrine_Table {

    /**
     * @return gaActiviteTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('gaActivite');
    }

    /**
     * Retrieve a collection of sports
     *
     * @param array $filters
     * @return Doctrine_Collection
     */
    public function getList($detail = ListDetail::NONE) {
        return $this->getListQuery($detail)->execute();
    }

    public function getListQuery($detail = ListDetail::NONE) {
        $q = Doctrine_Query::create()
                        ->from('gaActivite a')
                        ->where('a.is_visible = ?', true)
                        ->andWhere('a.date_fin > now()')
                        ->orderBy('a.nom');

        switch ( $detail ) {
            case ListDetail::FULL:
            case ListDetail::PARTIAL:
                $q->leftJoin('a.participants');
                break;
        }

        return $q;
    }

    /**
     * Retrieve a activite object<br/>
     * This is the function called by sfDoctrineRoute->getObject()
     *
     * @param Doctrine_Query $q
     * @return gaActivite
     */
    public function retrieveRouteObject(Doctrine_Query $q) {
        $a = $q->getRootAlias();

        return $q->leftJoin($a . '.coCotisants c')
                ->leftJoin($a . '.photos')
                ->execute();
    }

}