<?php

/**
 * phPhoto
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    BDS
 * @subpackage model
 * @author     Ludovic Henry
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class phPhoto extends BasephPhoto {

    /**
     * Get the url of the photo at the size you want. Will resize the photo if it have to.
     *
     * @param string $size the size of the photo you want
     * @return string the url to the photo
     */
    public function getUrl($size = 'grand') {
        if ( !in_array($size, array('petit', 'moyen', 'grand')) )
            return false;

        $basePath = sprintf('%s/photos', sfConfig::get('sf_upload_dir'));

        $filename = $this->getFilename();

        if ( $size === 'grand' ) {
            if ( !file_exists(sprintf('%s/grand/%s', $basePath, $filename)) )
                throw new Exception('File \'' . $filename . '\' doest not exist');
        } else {
            if ( !file_exists(sprintf('%s/%s/%s', $basePath, $size, $filename)) ) {
                $maxHeight = sfConfig::get(sprintf('app_image_%s_height', $size));
                $maxWidth = sfConfig::get(sprintf('app_image_%s_width', $size));

                $thumbnail = new sfThumbnail($maxWidth, $maxHeight);
                $thumbnail->loadFile(sprintf('%s/grand/%s', $basePath, $filename));
                $thumbnail->save(sprintf('%s/%s/%s', $basePath, $size, $filename));
            }
        }

        return sprintf('/uploads/photos/%s/%s', $size, $filename);
    }

    /**
     *
     * @return array
     */
    public function getUtilisations() {
        $utilisations = array();

        foreach ( $this->getSpSports() as $sport )
            $utilisations[] = ( string ) $sport;

        foreach ( $this->getGaActivites() as $activite )
            $utilisations[] = ( string ) $activite;

        if ( !is_null($this->getCoCotisant()) )
            $utilisations[] = ( string ) $this->getCoCotisant();

        return $utilisations;
    }

}