<?php

/**
 * spSportTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    BDS
 * @subpackage table
 * @author     Ludovic Henry
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class phPhotoTable extends Doctrine_Table {

    /**
     * @return phPhotoTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('phPhoto');
    }

    /**
     * The query to retrieve a collection of sports
     *
     * @param array $filters
     * @return Doctrine_Query
     */
    public function retrieveListQuery() {
        return $this->createQuery('p')
                ->leftJoin('p.gaActivites')
                ->leftJoin('p.spSports')
                ->leftJoin('p.coCotisant')
                ->orderBy('p.updated_at DESC');
    }

}