<?php

/**
 * spHoraireStatut
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    BDS
 * @subpackage model
 * @author     Ludovic Henry
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class spHoraireStatut extends BasespHoraireStatut {

    /**
     * The string representation of this object
     *
     * @return  string
     */
    public function __toString() {
        return $this->getNom();
    }

}
