<?php

/**
 * spSalle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    BDS
 * @subpackage model
 * @author     Ludovic Henry
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class spSalle extends BasespSalle {

    /**
     * The string representation of this object
     *
     * @return  string
     */
    public function __toString() {
        return $this->getNom();
    }

    /**
     * Get the following informations on this object : 'nom', 'adresse' and 'ville'
     * 
     * @return string informations on this object
     */
    public function getInformations() {
        return $this->getNom() . '<br/>' . $this->getAdresse() . ', ' . $this->getVille();
    }

}
