<?php

/**
 * spSportTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    BDS
 * @subpackage table
 * @author     Ludovic Henry
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class spSportTable extends Doctrine_Table {

    /**
     * @return spSportTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('spSport');
    }

    /**
     * Retrieve a collection of sports
     * 
     * @param array $filters
     * @return Doctrine_Collection
     */
    public function getList($detail = ListDetail::NONE) {
        return $this->getListQuery($detail)->execute();
    }

    public function getListQuery($detail = ListDetail::NONE) {
        $q = Doctrine_Query::create()
                        ->from('spSport sp')
                        ->where('is_visible = ?', true)
                        ->orderBy('sp.nom');

        switch ( $detail ) {
            case ListDetail::FULL:
            case ListDetail::PARTIAL:
                $q->leftJoin('sp.participants pa')
                    ->leftJoin('pa.coCotisant')
                    ->leftJoin('sp.horaires h')
                    ->leftJoin('h.salle');
                break;
        }

        return $q;
    }

    /**
     * Retrieve a collection of sports
     * This function is called in the backend
     * 
     * @param Doctrine_Query $q
     * @return Doctrine_Query
     */
    public function retrieveListBackend(Doctrine_Query $q) {
        $a = $q->getRootAlias();

        return $q->leftJoin($a . '.horaires')
                ->leftJoin($a . '.participants pa')
                ->leftJoin('pa.coCotisant');
    }

    /**
     * Retrieve a sport object<br/>
     * This is the function called by sfDoctrineRoute->getObject()
     * 
     * @param Doctrine_Query $q
     * @return spSport
     */
    public function retrieveRouteObject(Doctrine_Query $q) {
        $a = $q->getRootAlias();

        $q->leftJoin($a . '.horaires h')
                ->leftJoin('h.salle')
                ->leftJoin($a.'.participants p')
                ->leftJoin('p.coCotisant c')
                ->leftJoin('c.phPhoto')
                ->leftJoin($a . '.phPhotos')
                ->orderBy('h.jour');

        return $q->fetchOne();
    }

}