<?php

/**
 * stStatistiqueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class stStatistiqueTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object stStatistiqueTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('stStatistique');
    }
}