<?php

/**
 * suBugTrackerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class suBugTrackerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object suBugTrackerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('suBugTracker');
    }
}