<?php

/**
 * wmPieceJointeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class wmPieceJointeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object wmPieceJointeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('wmPieceJointe');
    }
}