<?php

/*
 * This file is part of the dcWidgetColorPickerPlugin package.
 * (c) Daniele Cesarini <daniele.cesarini@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * dcValidatorColorPicker validates the value generated by dcWidgetFormColorPicker
 *
 * @package    symfony
 * @subpackage validator
 * @author     Daniele Cesarini <daniele.cesarini@gmail.com>
 */

class dcValidatorColorPicker extends sfValidatorBase
{
  /**
   * @see sfValidatorBase
   */
  protected function doClean($value)
  {
    if (!preg_match('/^(?:(?:[a-f\d]{3}){1,2})$/i', $value)) {
      throw new sfValidatorError($this, 'invalid');
    }

    return $value;
  }
}
